/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author Patrick Rodrigues
 */
public class ApresentarSplashScreen2 extends javax.swing.JFrame {

    /**
     * Creates new form ApresentarSplashScreen2
     */
    public ApresentarSplashScreen2() {
        initComponents();

        new Thread() {

            public void run() {
                for (int i = 0; i < 101; i++) {
                    try {
                        sleep(50);
                        jProgressBarBarraCarregar.setValue(i);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(null, "Erro! Tente execultar mais tarde.  " + ex.getMessage());
                    }

                }
                //new Principal().setVisible(true);
                setVisible(false);
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarBarraCarregar = new javax.swing.JProgressBar();
        jLabelCarregando = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jProgressBarBarraCarregar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jProgressBarBarraCarregar.setForeground(new java.awt.Color(0, 51, 204));
        jProgressBarBarraCarregar.setAlignmentX(0.0F);
        jProgressBarBarraCarregar.setAlignmentY(0.0F);
        jProgressBarBarraCarregar.setPreferredSize(new java.awt.Dimension(146, 16));
        jProgressBarBarraCarregar.setStringPainted(true);
        getContentPane().add(jProgressBarBarraCarregar);
        jProgressBarBarraCarregar.setBounds(300, 430, 146, 16);

        jLabelCarregando.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelCarregando.setForeground(new java.awt.Color(0, 0, 204));
        jLabelCarregando.setText("Carregando...");
        getContentPane().add(jLabelCarregando);
        jLabelCarregando.setBounds(330, 410, 80, 16);

        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/POO2.jpg"))); // NOI18N
        getContentPane().add(jLabelImage);
        jLabelImage.setBounds(-10, 0, 470, 450);

        setSize(new java.awt.Dimension(450, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresentarSplashScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresentarSplashScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresentarSplashScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresentarSplashScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresentarSplashScreen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCarregando;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JProgressBar jProgressBarBarraCarregar;
    // End of variables declaration//GEN-END:variables
}
