/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import dao.ServidorDAO;
import javax.swing.JOptionPane;
import model.Dependentes;
import model.Endereco;
import model.Servidor;

/**
 *
 * @author Lord Devil Hunter
 */
public class CadastroServidor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroServidor
     */
    Servidor servidor;
    Endereco endereco;
    Dependentes dependentes;
    
    ServidorDAO sDao = new ServidorDAO();
        
    public CadastroServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane16 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel499 = new javax.swing.JLabel();
        jLabel500 = new javax.swing.JLabel();
        jLabel501 = new javax.swing.JLabel();
        jLabel502 = new javax.swing.JLabel();
        jLabel503 = new javax.swing.JLabel();
        imgIfpiLogo14 = new javax.swing.JLabel();
        jLabel504 = new javax.swing.JLabel();
        jlbNome14 = new javax.swing.JLabel();
        txfNomeServ = new javax.swing.JTextField();
        jlbSiaepi14 = new javax.swing.JLabel();
        txfSiaepi = new javax.swing.JTextField();
        jlbCargo12 = new javax.swing.JLabel();
        txfCargo = new javax.swing.JTextField();
        jLabel505 = new javax.swing.JLabel();
        txfDataEmissaoCargo = new javax.swing.JTextField();
        jLabel506 = new javax.swing.JLabel();
        txfDataNascimentoServ = new javax.swing.JTextField();
        jLabel507 = new javax.swing.JLabel();
        txfNaturalidadeServ = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel508 = new javax.swing.JLabel();
        txfEstadoCivilServ = new javax.swing.JTextField();
        jLabel509 = new javax.swing.JLabel();
        jLabel510 = new javax.swing.JLabel();
        txfUF = new javax.swing.JTextField();
        jLabel511 = new javax.swing.JLabel();
        txfCidade = new javax.swing.JTextField();
        jLabel512 = new javax.swing.JLabel();
        txfBairro = new javax.swing.JTextField();
        jLabel513 = new javax.swing.JLabel();
        txfRua = new javax.swing.JTextField();
        jLabel514 = new javax.swing.JLabel();
        txfNumeroDaCasa = new javax.swing.JTextField();
        jLabel515 = new javax.swing.JLabel();
        txfTelefone = new javax.swing.JTextField();
        jLabel516 = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        jLabel517 = new javax.swing.JLabel();
        txfCtps = new javax.swing.JTextField();
        jLabel518 = new javax.swing.JLabel();
        txfSerieCtps = new javax.swing.JTextField();
        jLabel519 = new javax.swing.JLabel();
        txfDataEmissaoCtps = new javax.swing.JTextField();
        jLabel520 = new javax.swing.JLabel();
        txfnumPisPasep = new javax.swing.JTextField();
        jLabel521 = new javax.swing.JLabel();
        txfDataCadastroPasep = new javax.swing.JTextField();
        jLabel522 = new javax.swing.JLabel();
        txfIdentidade = new javax.swing.JTextField();
        jLabel523 = new javax.swing.JLabel();
        txfOrgao = new javax.swing.JTextField();
        jLabel524 = new javax.swing.JLabel();
        txfDataEmissaoIdentidade = new javax.swing.JTextField();
        jLabel525 = new javax.swing.JLabel();
        txfNumTituloServ = new javax.swing.JTextField();
        jLabel526 = new javax.swing.JLabel();
        txfNumSecaoTitulo = new javax.swing.JTextField();
        jLabel527 = new javax.swing.JLabel();
        txfZonaTitulo = new javax.swing.JTextField();
        jLabel528 = new javax.swing.JLabel();
        txfNumCpfServ = new javax.swing.JTextField();
        jLabel529 = new javax.swing.JLabel();
        txfCertMilitar = new javax.swing.JTextField();
        jLabel530 = new javax.swing.JLabel();
        txfNomePai = new javax.swing.JTextField();
        jLabel531 = new javax.swing.JLabel();
        txfNomeMae = new javax.swing.JTextField();
        jLabel532 = new javax.swing.JLabel();
        txfGrauDeInstrucao = new javax.swing.JTextField();
        jLabel533 = new javax.swing.JLabel();
        txfAreaDeFormacao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        txfNomeDependente = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txfDataNascimentoDependente = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txfParentescoDependente = new javax.swing.JTextField();
        btnAdicionarDependente = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        CaixaSexo = new javax.swing.JComboBox<String>();
        jButton = new javax.swing.JButton();
        caixaDeficFisic = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseEntered(evt);
            }
        });

        jLabel499.setText("INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DO");

        jLabel500.setText("PIAUI");

        jLabel501.setText("CAMPUS PARNAÍBA");

        jLabel502.setText("COORDENAÇÃO DE RECURSOS HUMANOS");

        jLabel503.setText("FICHA DE CADASTRO DE SERVIDORES");

        imgIfpiLogo14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ifpi02.png"))); // NOI18N

        jLabel504.setText("MINISTERIO DA EDUCAÇÃO");

        jlbNome14.setText("NOME:");

        jlbSiaepi14.setText("SIAEPI:");

        jlbCargo12.setText("CARGO:");

        jLabel505.setText("DATA DE ADMISSÃO:");

        jLabel506.setText("DATA NASCIMENTO:");

        jLabel507.setText("NATURALIDADE:");

        jLabel508.setText("ESTADO CIVIL:");

        jLabel509.setText("DEFICIENTE FíSICO?");

        jLabel510.setText("UF:");

        jLabel511.setText("CIDADE:");

        jLabel512.setText("BAIRRO:");

        jLabel513.setText("RUA:");

        jLabel514.setText("NÚMERO DA CASA:");

        jLabel515.setText("TELEFONE(S) PARA CONTATO:");

        jLabel516.setText("E-MAIL:");

        jLabel517.setText("CTPS Nº:");

        jLabel518.setText("SÉRIE:");

        jLabel519.setText("EMISSÃO EM:");

        jLabel520.setText("PIS/PASEP N°:");

        jLabel521.setText("CADASTRADO EM:");

        jLabel522.setText("IDENTIDADE:");

        jLabel523.setText("ORGÃO:");

        jLabel524.setText("EMISSÃO EM:");

        jLabel525.setText("N.° TÍTULO");

        jLabel526.setText("SEÇÃO:");

        jLabel527.setText("ZONA/UF:");

        jLabel528.setText("CPF N.°:");

        jLabel529.setText("CERT. MILITAR:");

        jLabel530.setText("NOME DO PAI:");

        jLabel531.setText("NOME DA MÃE:");

        jLabel532.setText("GRAU DE INSTRUÇÃO:");

        jLabel533.setText("ÁREA DE FORMAÇÃO:");

        btnSalvar.setBackground(new java.awt.Color(153, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Nirmala UI", 2, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 204));
        btnSalvar.setText("SALVAR");
        btnSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel49.setText("DEPENDENTE:");

        txfNomeDependente.setEnabled(false);

        jLabel50.setText("D. DE NASCIMENTO:");

        txfDataNascimentoDependente.setEnabled(false);

        jLabel51.setText("PARENTESCO:");

        txfParentescoDependente.setEnabled(false);

        btnAdicionarDependente.setText("ADICIONAR");
        btnAdicionarDependente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionarDependente.setEnabled(false);

        jLabel52.setText("SEXO:");

        CaixaSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        CaixaSexo.setToolTipText("");
        CaixaSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CaixaSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton.setBackground(new java.awt.Color(153, 153, 153));
        jButton.setFont(new java.awt.Font("Nirmala UI", 2, 14)); // NOI18N
        jButton.setForeground(new java.awt.Color(102, 204, 0));
        jButton.setText("VOLTAR");
        jButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        caixaDeficFisic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));
        caixaDeficFisic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caixaDeficFisic.setMinimumSize(new java.awt.Dimension(71, 20));
        caixaDeficFisic.setPreferredSize(new java.awt.Dimension(71, 20));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel513)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfRua))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jlbNome14)
                                        .addGap(11, 11, 11)
                                        .addComponent(txfNomeServ))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel508)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfEstadoCivilServ))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel506)
                                        .addGap(4, 4, 4)
                                        .addComponent(txfDataNascimentoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel507)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfNaturalidadeServ))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jlbCargo12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfCargo))))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel511)
                                .addGap(4, 4, 4)
                                .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel512)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfBairro)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel514, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel505, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel510, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel509, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbSiaepi14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfSiaepi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfDataEmissaoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaixaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(caixaDeficFisic, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txfNumeroDaCasa)
                                .addComponent(txfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel525)
                                .addGap(4, 4, 4)
                                .addComponent(txfNumTituloServ, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel526)
                                .addGap(187, 187, 187)
                                .addComponent(jLabel527))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(imgIfpiLogo14)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel504)
                                    .addComponent(jLabel499)
                                    .addComponent(jLabel500)
                                    .addComponent(jLabel501)
                                    .addComponent(jLabel502)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(440, 440, 440)
                                .addComponent(jLabel503))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(440, 440, 440)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(4, 4, 4)
                                .addComponent(txfNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfDataNascimentoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfParentescoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdicionarDependente, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel533)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfAreaDeFormacao))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel532)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrauDeInstrucao))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel516)
                                .addGap(10, 10, 10)
                                .addComponent(txfEmail))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel515)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfTelefone))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel522)
                                        .addGap(4, 4, 4)
                                        .addComponent(txfIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel523)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel524))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfNumSecaoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                                                .addComponent(jLabel528)
                                                .addGap(4, 4, 4)
                                                .addComponent(txfNumCpfServ, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel529)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfDataEmissaoIdentidade)
                                    .addComponent(txfZonaTitulo)
                                    .addComponent(txfCertMilitar)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel520)
                                        .addGap(4, 4, 4)
                                        .addComponent(txfnumPisPasep, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel521))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel517)
                                        .addGap(4, 4, 4)
                                        .addComponent(txfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel518)
                                        .addGap(4, 4, 4)
                                        .addComponent(txfSerieCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel519)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfDataEmissaoCtps)
                                    .addComponent(txfDataCadastroPasep)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel531)
                                    .addComponent(jLabel530))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNomePai)
                                    .addComponent(txfNomeMae))))))
                .addGap(1, 1, 1))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgIfpiLogo14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel504)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel499)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel500)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel501)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel502)))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel503)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNomeServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jlbNome14)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jlbCargo12)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfDataNascimentoServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel506))
                            .addComponent(txfNaturalidadeServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel507)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfEstadoCivilServ, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel508))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel511)
                                    .addComponent(jLabel512))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel513)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfSiaepi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbSiaepi14))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfDataEmissaoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel505))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CaixaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(caixaDeficFisic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel509))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel510))
                                .addGap(6, 6, 6)
                                .addComponent(txfNumeroDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel514, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3)))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel515))
                    .addComponent(txfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel516))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSerieCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDataEmissaoCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel517)
                            .addComponent(jLabel518)
                            .addComponent(jLabel519))))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfnumPisPasep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfDataCadastroPasep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel520)
                            .addComponent(jLabel521))))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel523))
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfDataEmissaoIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel524))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel522)))
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel525))
                    .addComponent(txfNumTituloServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel526))
                    .addComponent(txfNumSecaoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfZonaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel527)))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfNumCpfServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCertMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel528)
                            .addComponent(jLabel529))))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel530))
                    .addComponent(txfNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel531))
                    .addComponent(txfNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel532))
                    .addComponent(txfGrauDeInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel533))
                    .addComponent(txfAreaDeFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel49))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50)
                            .addComponent(txfDataNascimentoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)
                            .addComponent(txfParentescoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarDependente))))
                .addGap(31, 31, 31)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(jButton)))
        );

        jScrollPane16.setViewportView(jPanel16);

        getContentPane().add(jScrollPane16, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseEntered

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // POSSIVEL CAGADA AQUI, QUALQUER COISA APAGAR!!!
        // POSSIVEL CAGADA AQUI, QUALQUER COISA APAGAR!!!
        // POSSIVEL CAGADA AQUI, QUALQUER COISA APAGAR!!!
        // POSSIVEL CAGADA AQUI, QUALQUER COISA APAGAR!!!
        servidor = new Servidor();
       
        servidor.setGrauInstrucaoServ(txfGrauDeInstrucao.getText());
        servidor.setAreaFormacaoServ(txfAreaDeFormacao.getText());
        servidor.setNomeServ(txfNomeServ.getText());
        servidor.setSIAPE(txfSiaepi.getText());
        servidor.setDataNascServ(txfDataNascimentoServ.getText());
        servidor.setEstadoCivilServ(txfEstadoCivilServ.getText());
        servidor.setNaturalidadeServ(txfNaturalidadeServ.getText());
        servidor.setDeficinteFisico(String.valueOf(caixaDeficFisic.getSelectedItem())); // <<<<<<------ Mudar para combobox
        servidor.setNomePaiServ(txfNomePai.getText());
        servidor.setNomeMaeServ(txfNomeMae.getText());
        servidor.setCargoServ(txfCargo.getText());
        servidor.setDataAdmissaoServ(txfDataEmissaoCargo.getText());

        servidor.setSerieCtpsServ(Long.parseLong(txfSerieCtps.getText()));
        servidor.setDataEmissaoCtpsServ(txfDataEmissaoCtps.getText());
        servidor.setNumPisPasepServ(Long.parseLong(txfnumPisPasep.getText()));
        servidor.setDataCadastroPisPasepServ(txfDataCadastroPasep.getText());
        servidor.setIdentidadeServ(Long.parseLong(txfIdentidade.getText()));
        servidor.setOrgaoIdentidadeServ(txfOrgao.getText());
        servidor.setDataEmissaoIdentidadeServ(txfDataEmissaoIdentidade.getText());
        servidor.setNumTituloServ(Long.parseLong(txfNumTituloServ.getText()));
        servidor.setNumSessaoTituloServ(Long.parseLong(txfNumTituloServ.getText()));
        servidor.setZonaTituloServ(txfZonaTitulo.getText());
        servidor.setNumCpfServ(txfNumCpfServ.getText());
        servidor.setCertMilitarServ(Long.parseLong(txfCertMilitar.getText()));

        //Pegando dados para a classe endereco
        endereco = new Endereco();

        endereco.setUF(txfUF.getText());
        endereco.setCidade(txfCidade.getText());
        endereco.setBairro(txfBairro.getText());
        endereco.setNumero(Integer.parseInt(txfNumeroDaCasa.getText()));
        endereco.setRua(txfRua.getText());
        endereco.setEmail(txfEmail.getText());
        endereco.setTelefone(txfTelefone.getText());

        //Pegando dependentes para a classe dependentes
        dependentes = new Dependentes();

        dependentes.setNomeDependente(txfNomeDependente.getText());
        dependentes.setDataNascimentoDependente(txfDataNascimentoDependente.getText());
        dependentes.setParentesco(txfParentescoDependente.getText());
        

        try {
            //Pegando dados para a classe servidor
            sDao.salvar(servidor);
            JOptionPane.showMessageDialog(this, "Servidor inserido");

            /// POSSIVEIS ERROS ABAIXO
            /// POSSIVEIS ERROS ABAIXO
            /// POSSIVEIS ERROS ABAIXO
            /// POSSIVEIS ERROS ABAIXO

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Deu ruim");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CaixaSexo;
    private javax.swing.JButton btnAdicionarDependente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox caixaDeficFisic;
    private javax.swing.JLabel imgIfpiLogo14;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel499;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel500;
    private javax.swing.JLabel jLabel501;
    private javax.swing.JLabel jLabel502;
    private javax.swing.JLabel jLabel503;
    private javax.swing.JLabel jLabel504;
    private javax.swing.JLabel jLabel505;
    private javax.swing.JLabel jLabel506;
    private javax.swing.JLabel jLabel507;
    private javax.swing.JLabel jLabel508;
    private javax.swing.JLabel jLabel509;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel510;
    private javax.swing.JLabel jLabel511;
    private javax.swing.JLabel jLabel512;
    private javax.swing.JLabel jLabel513;
    private javax.swing.JLabel jLabel514;
    private javax.swing.JLabel jLabel515;
    private javax.swing.JLabel jLabel516;
    private javax.swing.JLabel jLabel517;
    private javax.swing.JLabel jLabel518;
    private javax.swing.JLabel jLabel519;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel520;
    private javax.swing.JLabel jLabel521;
    private javax.swing.JLabel jLabel522;
    private javax.swing.JLabel jLabel523;
    private javax.swing.JLabel jLabel524;
    private javax.swing.JLabel jLabel525;
    private javax.swing.JLabel jLabel526;
    private javax.swing.JLabel jLabel527;
    private javax.swing.JLabel jLabel528;
    private javax.swing.JLabel jLabel529;
    private javax.swing.JLabel jLabel530;
    private javax.swing.JLabel jLabel531;
    private javax.swing.JLabel jLabel532;
    private javax.swing.JLabel jLabel533;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JLabel jlbCargo12;
    private javax.swing.JLabel jlbNome14;
    private javax.swing.JLabel jlbSiaepi14;
    private javax.swing.JTextField txfAreaDeFormacao;
    private javax.swing.JTextField txfBairro;
    private javax.swing.JTextField txfCargo;
    private javax.swing.JTextField txfCertMilitar;
    private javax.swing.JTextField txfCidade;
    private javax.swing.JTextField txfCtps;
    private javax.swing.JTextField txfDataCadastroPasep;
    private javax.swing.JTextField txfDataEmissaoCargo;
    private javax.swing.JTextField txfDataEmissaoCtps;
    private javax.swing.JTextField txfDataEmissaoIdentidade;
    private javax.swing.JTextField txfDataNascimentoDependente;
    private javax.swing.JTextField txfDataNascimentoServ;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfEstadoCivilServ;
    private javax.swing.JTextField txfGrauDeInstrucao;
    private javax.swing.JTextField txfIdentidade;
    private javax.swing.JTextField txfNaturalidadeServ;
    private javax.swing.JTextField txfNomeDependente;
    private javax.swing.JTextField txfNomeMae;
    private javax.swing.JTextField txfNomePai;
    private javax.swing.JTextField txfNomeServ;
    private javax.swing.JTextField txfNumCpfServ;
    private javax.swing.JTextField txfNumSecaoTitulo;
    private javax.swing.JTextField txfNumTituloServ;
    private javax.swing.JTextField txfNumeroDaCasa;
    private javax.swing.JTextField txfOrgao;
    private javax.swing.JTextField txfParentescoDependente;
    private javax.swing.JTextField txfRua;
    private javax.swing.JTextField txfSerieCtps;
    private javax.swing.JTextField txfSiaepi;
    private javax.swing.JTextField txfTelefone;
    private javax.swing.JTextField txfUF;
    private javax.swing.JTextField txfZonaTitulo;
    private javax.swing.JTextField txfnumPisPasep;
    // End of variables declaration//GEN-END:variables
}
